apiVersion: apps/v1
kind: Deployment
metadata:
  name: autosnap-backup
  labels:
    name: backup
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: autosnap
  template:
    metadata:
      labels:
        app: autosnap
    spec:
      volumes:
        - name: google-application-credentials
          secret:
            secretName: autosnap-credentials
      containers:
        - name: backup
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: PROJECT
              value: {{ .Values.project }}
            - name: DISK
              value: {{ .Values.disk }}
            - name: ZONE
              value: {{ .Values.zone }}
            - name: SNAPSHOT_NAME
              value: {{ .Values.snapshotName }}
            - name: INTERVAL_MINUTES
              value: "{{ .Values.interval }}"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/key.json"
          command: ['/bin/bash','-c','python app.py']
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: google-application-credentials
              mountPath: "/var/secrets/google"