{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "patroni.fullname" . }}-role
  labels:
    app: {{ template "patroni.name" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - configmaps
    verbs:
      - list
      - patch
      - watch
  - apiGroups: [""]
    resources:
      - endpoints
    verbs:
      - create
      - list
      - watch
      - patch
{{- end }}
